apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: auth-service-base

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- hpa.yaml
- networkpolicy.yaml
- poddisruptionbudget.yaml

commonLabels:
  app.kubernetes.io/name: auth-service
  app.kubernetes.io/component: auth
  app.kubernetes.io/part-of: dreamscape

images:
- name: ghcr.io/dreamscape/auth
  newTag: latest