apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  labels:
    app: auth-service
    component: auth
    part-of: dreamscape
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service