#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - htop
  - net-tools

write_files:
  - path: /usr/local/bin/install-k3s-agent.sh
    content: |
      #!/bin/bash
      set -e
      
      echo "Installing K3s agent..."
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.28.5+k3s1" K3S_URL="${server_url}" K3S_TOKEN="${k3s_token}" sh -s - agent \
        --kubelet-arg="cloud-provider=external" \
        --node-label="node.dreamscape.com/role=agent" \
        --node-label="node.dreamscape.com/environment=${cluster_name}"
      
      echo "K3s agent installation complete!"
    permissions: '0755'
    owner: root:root

runcmd:
  - sleep 60  # Wait for server to be ready
  - /usr/local/bin/install-k3s-agent.sh > /var/log/k3s-install.log 2>&1

final_message: "K3s agent node ${node_index} installation completed successfully!"