name: Deploy Simple

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy avec contournement
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST_STAGING }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            docker stop dreamscape-frontend-staging 2>/dev/null || true
            docker rm dreamscape-frontend-staging 2>/dev/null || true
            docker pull dreamscape/frontend:latest
            docker run -d --name dreamscape-frontend-staging --restart unless-stopped -p 80:80 -e NODE_ENV=staging dreamscape/frontend:latest
            sleep 5
            docker ps | grep dreamscape-frontend-staging